apiVersion: v1
kind: Secret
metadata:
  name: blog-app-secrets
  namespace: blog-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://bloguser:blogpassword@postgres-service:5432/blogdb"
  AUTH_SECRET: "devops-blog-app-secret-key-2024-production"
