apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
  namespace: blog-app
  labels:
    app: blog-app
spec:
  type: NodePort
  selector:
    app: blog-app
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
  sessionAffinity: ClientIP
